spring: # todo - 3. imported property file
  datasource:
    username: "${DB_USERNAME:jira}"
    password: "${DB_PASSWORD:JiraRush}"
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: "${GITHUB_CLIENT_ID:3d0d8738e65881fff266}"
            client-secret: "${GITHUB_CLIENT_SECRET:0f97031ce6178b7dfb67a6af587f37e222a16120}"
          google:
            client-id: "${GOOGLE_CLIENT_ID:329113642700-f8if6pu68j2repq3ef6umd5jgiliup60.apps.googleusercontent.com}"
            client-secret: "${GOOGLE_CLIENT_SECRET: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}"
          gitlab:
            client-id: "${GITLAB_CLIENT_ID:b8520a3266089063c0d8261cce36971defa513f5ffd9f9b7a3d16728fc83a494}"
            client-secret: "${GITLAB_CLIENT_SECRET:e72c65320cf9d6495984a37b0f9cc03ec46be0bb6f071feaebbfe75168117004}"
  mail:
    host: "${MAIL_HOST:smtp.gmail.com}"
    username: "${MAIL_USERNAME:jira4jr@gmail.com}"
    password: "${MAIL_PASSWORD:zdfzsrqvgimldzyj}"
    port: "${MAIL_PORT:587}"