app:
  host-url: ${HOST_URL}
  test-mail: ${TEST_MAIL}
  templates-update-cache: 5s
  mail-sending-props:
    core-pool-size: 8
    max-pool-size: 100

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # 1 day
      refresh-token:
        expiration: 604800000 # 7 days

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  mail:
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
    host: ${SPRING_MAIL_HOST}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    port: ${SPRING_MAIL_PORT}

  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20

  liquibase:
    changeLog: "classpath:db/changelog.sql"

  jackson:
    visibility:
      field: any
      getter: none
      setter: none
      is-getter: none

  cache:
    cache-names: users
    caffeine.spec: maximumSize=10000,expireAfterAccess=5m
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: ${GITHUB_SCOPE}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: ${GOOGLE_SCOPE}
          gitlab:
            client-id: ${GITLAB_CLIENT_ID}
            client-secret: ${GITLAB_SECRET}
            client-name: ${GITLAB_NAME}
            redirect-uri: ${GITLAB_REDIRECT_URI}
            authorization-grant-type: ${GITLAB_AUTHORIZATION_GRANT_TYPE}
            scope: ${GITLAB_SCOPE}
        provider:
          gitlab:
            authorization-uri: https://gitlab.com/oauth/authorize
            token-uri: https://gitlab.com/oauth/token
            user-info-uri: https://gitlab.com/api/v4/user
            user-name-attribute: email
  sql:
    init:
      mode: always

#  thymeleaf.check-template-location: false
  thymeleaf:
    cache: true
    prefix: classpath:/template/view/
    suffix: .html

  messages:
    basename: language/messages

logging:
  level:
    root: WARN
    com.javarush.jira: DEBUG
    com.javarush.jira.common.config.MvcConfig: WARN
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: DEBUG

server:
  forward-headers-strategy: framework
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
springdoc.swagger-ui.path: /doc
