# TODO : 4/ add dev profile to run full app with h2 db in mem
spring.cache.type: none
spring:
  sql:
    init:
      mode: always
  liquibase:
    change-log: db/changelog.xml
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE;
    username: sa
    password: