# TODO 4 - add test profile to run app with h2 db
spring.cache.type: none
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;NON_KEYWORDS=VALUE
    username: sa
    password:
