spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_GITHUB_SECRET}
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_SECRET}
          gitlab:
            client-id: ${OAUTH2_GITLAB_CLIENT_ID}
            client-secret: ${OAUTH2_GITLAB_SECRET}
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587