spring:
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${OAUTH2_REGISTRATION_GITHUB_CLIENT_ID}
            client-secret: ${OAUTH2_REGISTRATION_GITHUB_CLIENT_SECRET}

          google:
            client-id: ${OAUTH2_REGISTRATION_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_REGISTRATION_GOOGLE_CLIENT_SECRET}

          gitlab:
            client-id: ${OAUTH2_REGISTRATION_GITLAB_CLIENT_ID}
            client-secret: ${OAUTH2_REGISTRATION_GITLAB_CLIENT_SECRET}

  mail:
    properties:
      mail:
        smtp:
          starttls:
            enable: ${MAIL_PROPERTIES_SMTP_STARTTLS_ENABLE}
          auth: ${MAIL_PROPERTIES_SMTP_AUTH}
    host: ${MAIL_PROPERTIES_HOST}
    username: ${MAIL_PROPERTIES_USERNAME}
    password: ${MAIL_PROPERTIES_PASSWORD}
    port: ${MAIL_PROPERTIES_PORT}

