#TODO Transfer security properties in new place with environment variables
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/jira}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}

          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

          gitlab:
            client-id: ${GITLAB_CLIENT_ID}
            client-secret: ${GITLAB_CLIENT_SECRET}

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
