# template for server
app:
  host-url: http://localhost
spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/jira
    # jira-db - docker compose container name
    url: jdbc:postgresql://jira-db:5432/jira
    username: jira
    password: JiraRush

